set(DOOM_FILES
	./doom/p_maputl.c
	./doom/r_sky.c
	./doom/v_video.c
	./doom/r_main.c
	./doom/st_stuff.c
	./doom/r_bsp.c
	./doom/info.c
	./doom/am_map.c
	./doom/p_enemy.c
	./doom/i_main.c
	./doom/r_segs.c
	./doom/p_plats.c
	./doom/w_wad.c
	./doom/p_inter.c
	./doom/doomdef.c
	./doom/hu_stuff.c
	./doom/p_switch.c
	./doom/sounds.c
	./doom/dstrings.c
	./doom/i_sound.c
	./doom/g_game.c
	./doom/m_menu.c
	./doom/p_user.c
	./doom/d_net.c
	./doom/p_tick.c
	./doom/p_doors.c
	./doom/m_swap.c
	./doom/i_video.c
	./doom/f_wipe.c
	./doom/s_sound.c
	./doom/p_map.c
	./doom/m_misc.c
	./doom/p_mobj.c
	./doom/p_floor.c
	./doom/tables.c
	./doom/m_fixed.c
	./doom/r_things.c
	./doom/wi_stuff.c
	./doom/st_lib.c
	./doom/p_spec.c
	./doom/m_argv.c
	./doom/p_ceilng.c
	./doom/i_system.c
	./doom/f_finale.c
	./doom/r_plane.c
	./doom/p_setup.c
	./doom/z_zone.c
	./doom/m_bbox.c
	./doom/i_net.c
	./doom/hu_lib.c
	./doom/p_telept.c
	./doom/m_random.c
	./doom/d_main.c
	./doom/p_sight.c
	./doom/r_draw.c
	./doom/d_items.c
	./doom/m_cheat.c
	./doom/p_lights.c
	./doom/doomstat.c
	./doom/p_pspr.c
	./doom/p_saveg.c
	./doom/r_data.c
)